steps:
  # Paso 1: Construir la imagen del contenedor usando el Dockerfile de tu repo
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-east1-docker.pkg.dev/gen-lang-client-0497669167/app-repo/frontend-service:$COMMIT_SHA', 
      '.'
    ]

  # Paso 2: Subir la imagen al Artifact Registry que creamos antes
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-east1-docker.pkg.dev/gen-lang-client-0497669167/app-repo/frontend-service:$COMMIT_SHA'
    ]

  # Paso 3: Desplegar la nueva imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image'
      - 'us-east1-docker.pkg.dev/gen-lang-client-0497669167/app-repo/frontend-service:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Imágenes que se generan en este proceso
images:
  - 'us-east1-docker.pkg.dev/gen-lang-client-0497669167/app-repo/frontend-service:$COMMIT_SHA'
